# This file should NOT be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/wazo-agentd/conf.d/

# Owner of the process
user: wazo-agentd

# Change the log level to debug level.
debug: false

# Log file.
logfile: /var/log/wazo-agentd.log

# PID file.
pidfile: /var/run/wazo-agentd/wazo-agentd.pid

# Database connection informations.
db_uri: postgresql://asterisk:proformatique@localhost/asterisk

auth:
  host: localhost
  port: 9497
  verify_certificate: /usr/share/xivo-certs/server.crt

# AMI (Asterisk Manager Interface) connection informations.
ami:
  host: localhost
  username: wazo_agentd
  password: die0Ahn8tae

# Bus connection to the AMQP server
bus:
  username: guest
  password: guest
  host: localhost
  port: 5672
  exchange_name: xivo
  exchange_type: topic

# REST API server
rest_api:

  https:
    # Listening address
    listen: 0.0.0.0

    # Listening port
    port: 9493

    # SSL files
    certificate: /usr/share/xivo-certs/server.crt
    private_key: /usr/share/xivo-certs/server.key

  #CORS configuration. See Flask-CORS documentation for other values.
  cors:

    #Enabled by default
    enabled: true

    #Allow JSON preflight requests
    allow_headers: [Content-Type, X-Auth-Token, Wazo-Tenant]

# Service discovery configuration. all time intervals are in seconds
service_discovery:
  # the address that will be received by other services using service discovery.
  # use "advertise_address: auto" to enable ip address detection based on
  # advertise_address_interface
  advertise_address: auto
  # if advertise_address is "auto" this interface will be used to find the ip
  # address to advertise. ignored otherwise
  advertise_address_interface: eth0
  advertise_port: 9493
  # the number of seconds that consul will wait between 2 ttl messages to mark
  # this service as up
  ttl_interval: 30
  # the time interval before the service sends a new ttl message to consul
  refresh_interval: 27
  # the time interval to detect that the service is running when starting
  retry_interval: 2
  extra_tags: []
